usuario_rol:
    resource: "@UsuarioBundle/Resources/config/routing/rol.yml"
    prefix:   /roles

usuario_homepage:
    path:     /
    defaults: { _controller: UsuarioBundle:Default:index }

cambiar-password:
    path:     /usuarios/{id}/cambiar-password
    defaults: { _controller: UsuarioBundle:CambiarPassword:cambiarPassword }
