<?php

namespace AppBundle\Repository;

/**
 * EstadisticaFinalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadisticaFinalRepository extends \Doctrine\ORM\EntityRepository
{
}
