<?php

namespace AppBundle\Repository;

/**
 * EstadisticasTemporalesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadisticasTemporalesRepository extends \Doctrine\ORM\EntityRepository
{
}
