<?php

namespace AppBundle\Repository;

/**
 * IntervencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntervencionRepository extends \Doctrine\ORM\EntityRepository
{

    public function getQb()
    {
        return $this->createQueryBuilder('interv');
    }

    public function getUltimasIntervencionesByPozo($pozo)
    {
        $qb = $this->getQb()
            ->innerJoin('interv.pozo','pozo')
            ->where('pozo = :pozo')
            ->orderBy('interv.fecha','DESC')
            ->orderBy('interv.fechaCreacion','DESC');

        $qb->setParameter('pozo',$pozo);

        return $qb;
    }


}
