<?php

namespace AppBundle\Repository;

/**
 * NovedadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NovedadRepository extends \Doctrine\ORM\EntityRepository
{
    public function getQb()
    {
        return $this->createQueryBuilder('nov');
    }

    public function getNovedadesByIntervencion($intervencion)
    {
        $qb = $this->getQb();

        $qb->where('nov.intervencion = :intervencion')
            ->orderBy('nov.fin', 'ASC')
            ->setParameter('intervencion', $intervencion);


        return $qb;
    }

}
