# redirecting the root
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin
        permanent: true

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:  /admin

usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


