# redirecting the root
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin
        permanent: true

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:  /admin


app_commands:
    resource: "@AppBundle/Controller/CommandsController.php"
    type:     annotation

usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"


