estadistica_operaciones_por_equipo:
    path:     operaciones_por_equipo
    defaults: { _controller: AppBundle:estadistica:operacionesPorEquipo }
    methods: [GET]

estadistica_operaciones_por_yacimiento:
    path:     operaciones_por_yacimiento
    defaults: { _controller: AppBundle:estadistica:operacionesPorYacimiento }
    methods: [GET]

estadistica_promedios_canos_hora:
    path:     promedios_canos_hora
    defaults: { _controller: AppBundle:estadistica:promediosCanosHora }
    methods: [GET]

estadistica_promedios_varillas_hora:
    path:     promedios_varillas_hora
    defaults: { _controller: AppBundle:Estadistica:promediosVarillasHora }
    methods: [GET]

estadistica_factor_tiempo_util:
    path:     factor_tiempo_util
    defaults: { _controller: AppBundle:estadistica:factorTiempoUtil }
    methods: [GET]


estadistica_operaciones_individuales_por_yacimiento:
    path:     operaciones_individuales_por_yacimiento
    defaults: { _controller: AppBundle:Estadistica:operacionesIndividualesPorYacimiento }
    methods: [GET]

estadistica_promedios_individuales_canos_hora:
    path:     promedios_individuales_canos_hora
    defaults: { _controller: AppBundle:Estadistica:promediosIndividualesCanosHora }
    methods: [GET]

estadistica_promedios_individuales_varillas_hora:
    path:     promedios_individuales_varillas_hora
    defaults: { _controller: AppBundle:Estadistica:promediosIndividualesVarillasHora }
    methods: [GET]

estadistica_individuales_factor_tiempo_util:
    path:     individuales_factor_tiempo_util
    defaults: { _controller: AppBundle:estadistica:individualesFactorTiempoUtil }
    methods: [GET]