<?php

namespace OAuth2Bundle\Repository;

/**
 * OAuthUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OAuthAccessTokensRepository extends \Doctrine\ORM\EntityRepository
{

	public function getLastTokenByUser($user){

		$qb = $this->createQueryBuilder('oat')
			->where('oat.user = :user')

			->setMaxResults(1);

		$qb->setParameter('user',$user);

	}

}
