app_equipo:
        resource: "@AppBundle/Resources/config/routing/equipo.yml"
        prefix:   /equipo

app_compania:
        resource: "@AppBundle/Resources/config/routing/compania.yml"
        prefix:   /compania

app_persona:
    resource: "@AppBundle/Resources/config/routing/persona.yml"
    prefix:   /usuarios

dashboard:
    path: /
    defaults: { _controller: AppBundle:Default:index}
    methods: [GET]

#datos_en_vivo:
#    path:     ajax/datos_en_vivo
#    defaults: { _controller: AppBundle:Ajax:datosEnVivo }
#    methods: [GET]
